name: PR slash command template inserter

on:
  issue_comment:
    types: [created]

jobs:
  insert-template:
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/template ')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Get template name
        id: parse
        run: |
          # Expected comment example: /template feature
          key=$(echo "${{ github.event.comment.body }}" | awk '{print $2}')
          echo "key=$key" >> $GITHUB_OUTPUT

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read template file
        id: read
        run: |
          cat > read-template.mjs <<'EOF'

          import fs from "fs";
          const key = process.env.TEMPLATE_KEY;
          const file = `.github/PULL_REQUEST_TEMPLATE/${key}.md`;
          if (!fs.existsSync(file)) {
            process.stdout.write(`content=Template not found: ${file}\n`);
            process.exit(0);
          }
          const lines = fs.readFileSync(file, "utf8").replace(/\r/g, "").split("\n");
          const escaped = lines.map(l => l.replace(/"/g, '\\"'));
          const content = escaped.join("\\n");
          process.stdout.write(`content=${content}\n`);

          EOF
          node read-template.mjs >> "$GITHUB_OUTPUT"
        env:
          TEMPLATE_KEY: ${{ steps.parse.outputs.key }}

      - name: Get current PR body (curl)
        id: getpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
        run: |
          pr_json=$(curl -s \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/pulls/$NUMBER")

          body=$(echo "$pr_json" | jq -r '.body')

          # GITHUB_OUTPUT にマルチライン本文を安全に渡す
          {
            echo 'body<<EOF'
            echo "$body"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Update PR body (curl)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          TEMPLATE_CONTENT: ${{ steps.read.outputs.content }}
          ORIGINAL_BODY: ${{ steps.getpr.outputs.body }}
        run: |
          # 新しい本文を組み立て (テンプレートは既に \n エスケープ済み)
          # TEMPLATE_CONTENT 内の \n は実際の改行に変換してから結合したい場合:
          # template_real=$(printf "%b" "$TEMPLATE_CONTENT")
          # ここではそのまま利用 (表示上は \n が残る)
          new_body=$(printf "%s\n---\n(Original content below)\n%s" "$TEMPLATE_CONTENT" "$ORIGINAL_BODY")

          # jq を使って JSON 文字列として安全にエンコード
          payload=$(jq -Rn --arg b "$new_body" '{body: $b}')

          curl -s -X PATCH \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -d "$payload" \
            "https://api.github.com/repos/$REPO/pulls/$NUMBER"
